name: 'git-pile: env-setup'
description: 'Set up environment with needed tools'
author: 'Lucas De Marchi'
inputs:
  version:
    required: false
runs:
  using: 'composite'
  steps:
  - run: ${{ github.action_path }}/run.sh ${{ inputs.version }}
    shell: bash
